[project]
name = "blogcast-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai>=0.134.0",
    "crewai-tools>=0.48.0",
    "youtube-transcript-api==0.6.1",
    "yt-dlp==2023.11.14",
]
